_COMMON_RENAME = {
    "CNPJ_FUNDO_CLASSE": "cnpj_fundo",
    "DENOM_SOCIAL": "denom_social",
    "DT_COMPTC": "dt_comptc",
    "DT_CONFID_APLIC": "dt_confid_aplic",
    "EMISSOR_LIGADO": "emissor_ligado",
    "TP_APLIC": "tp_aplic",
    "TP_ATIVO": "tp_ativo",
    "TP_FUNDO_CLASSE": "tp_fundo_classe",
    "TP_NEGOC": "tp_negoc",
    "QT_AQUIS_NEGOC": "qt_aquis_negoc",
    "QT_POS_FINAL": "qt_pos_final",
    "QT_VENDA_NEGOC": "qt_venda_negoc",
    "VL_AQUIS_NEGOC": "vl_aquis_negoc",
    "VL_CUSTO_POS_FINAL": "vl_custo_pos_final",
    "VL_MERC_POS_FINAL": "vl_merc_pos_final",
    "VL_VENDA_NEGOC": "vl_venda_negoc",
}

BLC_TO_SILVER_MAP = {
    "blc_1": {
        **_COMMON_RENAME,
        "CD_ISIN": "cd_isin",
        "CD_SELIC": "cd_selic",
        "TP_TITPUB": "tp_titulo_pub",
        "DT_EMISSAO": "dt_emissao",
        "DT_VENC": "dt_venc",
    },
    "blc_2": {
        **_COMMON_RENAME,
        "CNPJ_FUNDO_CLASSE_COTA": "cnpj_fundo_cota",
        "ID_SUBCLASSE": "id_subclasse",
        "NM_FUNDO_CLASSE_SUBCLASSE_COTA": "nm_fundo_cota",
    },
    "blc_3": {
        **_COMMON_RENAME,
        "CD_SWAP": "cd_swap",
        "DS_SWAP": "ds_swap",
    },
    "blc_4": {
        **_COMMON_RENAME,
        "CD_ATIVO": "cd_ativo",
        "CD_ISIN": "cd_isin",
        "DS_ATIVO": "ds_ativo",
        "DT_FIM_VIGENCIA": "dt_fim_vigencia",
        "DT_INI_VIGENCIA": "dt_ini_vigencia",
    },
    "blc_5": {
        **_COMMON_RENAME,
        "AG_RISCO": "ag_risco",
        "CD_INDEXADOR_POSFX": "cd_indexador_posfx",
        "CNPJ_EMISSOR": "cpf_cnpj_emissor",
        "DS_INDEXADOR_POSFX": "ds_indexador_posfx",
        "DT_RISCO": "dt_risco",
        "DT_VENC": "dt_venc",
        "EMISSOR": "nm_emissor",
        "GRAU_RISCO": "grau_risco",
        "PR_CUPOM_POSFX": "pr_cupom_posfx",
        "PR_INDEXADOR_POSFX": "pr_indexador_posfx",
        "PR_TAXA_PREFX": "pr_taxa_prefx",
        "RISCO_EMISSOR": "risco_emissor",
        "TITULO_POSFX": "titulo_posfx",
    },
    "blc_6": {
        **_COMMON_RENAME,
        "CD_INDEXADOR_POSFX": "cd_indexador_posfx",
        "CNPJ_INSTITUICAO_FINANC_COOBR": "cnpj_coobrigacao",
        "CPF_CNPJ_EMISSOR": "cpf_cnpj_emissor",
        "DS_INDEXADOR_POSFX": "ds_indexador_posfx",
        "DT_VENC": "dt_venc",
        "EMISSOR": "nm_emissor",
        "PF_PJ_EMISSOR": "pf_pj_emissor",
        "PR_CUPOM_POSFX": "pr_cupom_posfx",
        "PR_INDEXADOR_POSFX": "pr_indexador_posfx",
        "PR_TAXA_PREFX": "pr_taxa_prefx",
        "TITULO_CETIP": "titulo_cetip",
        "TITULO_GARANTIA": "titulo_garantia",
        "TITULO_POSFX": "titulo_posfx",
    },
    "blc_7": {
        **_COMMON_RENAME,
        "AG_RISCO": "ag_risco",
        "BV_MERC": "bv_merc",
        "CD_ATIVO_BV_MERC": "cd_ativo_bv_merc",
        "CD_BV_MERC": "cd_bv_merc",
        "CD_PAIS": "cd_pais",
        "DS_ATIVO_EXTERIOR": "ds_ativo_exterior",
        "DT_RISCO": "dt_risco",
        "DT_VENC": "dt_venc",
        "EMISSOR": "nm_emissor",
        "GRAU_RISCO": "grau_risco",
        "INVEST_COLETIVO": "invest_coletivo",
        "INVEST_COLETIVO_GESTOR": "invest_coletivo_gestor",
        "PAIS": "pais",
        "QT_ATIVO_EXTERIOR": "qt_ativo_exterior",
        "RISCO_EMISSOR": "risco_emissor",
        "VL_ATIVO_EXTERIOR": "vl_ativo_exterior",
    },
    "blc_8": {
        **_COMMON_RENAME,
        "CPF_CNPJ_EMISSOR": "cpf_cnpj_emissor",
        "DS_ATIVO": "ds_ativo",
        "EMISSOR": "nm_emissor",
        "PF_PJ_EMISSOR": "pf_pj_emissor",
    },
}

SILVER_COLS_ORDER = [
    "cnpj_fundo", "denom_social", "tp_fundo_classe",
    "dt_comptc", "dt_confid_aplic", "ano_particao", "mes_particao",
    "bloco",
    "tp_ativo", "tp_aplic", "tp_negoc", "emissor_ligado",
    "cd_isin", "cd_selic", "tp_titulo_pub", "dt_emissao", "dt_venc",
    "id_subclasse", "cnpj_fundo_cota", "nm_fundo_cota",
    "cd_swap", "ds_swap",
    "cd_ativo", "ds_ativo", "dt_ini_vigencia", "dt_fim_vigencia",
    "cpf_cnpj_emissor", "nm_emissor", "pf_pj_emissor",
    "ag_risco", "grau_risco", "dt_risco", "risco_emissor",
    "cd_indexador_posfx", "ds_indexador_posfx", "titulo_posfx",
    "pr_cupom_posfx", "pr_indexador_posfx", "pr_taxa_prefx",
    "cnpj_coobrigacao", "titulo_cetip", "titulo_garantia",
    "cd_pais", "pais", "bv_merc", "cd_bv_merc", "cd_ativo_bv_merc",
    "ds_ativo_exterior", "invest_coletivo", "invest_coletivo_gestor",
    "qt_ativo_exterior", "vl_ativo_exterior",
    "qt_aquis_negoc", "qt_pos_final", "qt_venda_negoc",
    "vl_aquis_negoc", "vl_custo_pos_final", "vl_merc_pos_final", "vl_venda_negoc",
    "timestamp_dagrun", "timestamp_escrita",
]

SH_SCHEMA_SILVER = {
    "cnpj_fundo": {"nomes_origem": ["cnpj_fundo"], "tipo": "string"},
    "denom_social": {"nomes_origem": ["denom_social"], "tipo": "string"},
    "tp_fundo_classe": {"nomes_origem": ["tp_fundo_classe"], "tipo": "string"},
    "dt_comptc": {"nomes_origem": ["dt_comptc"], "tipo": "datetime64[us]"},
    "dt_confid_aplic": {"nomes_origem": ["dt_confid_aplic"], "tipo": "datetime64[us]"},
    "ano_particao": {"nomes_origem": ["ano_particao"], "tipo": "int32"},
    "mes_particao": {"nomes_origem": ["mes_particao"], "tipo": "int32"},
    "bloco": {"nomes_origem": ["bloco"], "tipo": "string"},
    "tp_ativo": {"nomes_origem": ["tp_ativo"], "tipo": "string"},
    "tp_aplic": {"nomes_origem": ["tp_aplic"], "tipo": "string"},
    "tp_negoc": {"nomes_origem": ["tp_negoc"], "tipo": "string"},
    "emissor_ligado": {"nomes_origem": ["emissor_ligado"], "tipo": "string"},
    "cd_isin": {"nomes_origem": ["cd_isin"], "tipo": "string"},
    "cd_selic": {"nomes_origem": ["cd_selic"], "tipo": "string"},
    "tp_titulo_pub": {"nomes_origem": ["tp_titulo_pub"], "tipo": "string"},
    "dt_emissao": {"nomes_origem": ["dt_emissao"], "tipo": "datetime64[us]"},
    "dt_venc": {"nomes_origem": ["dt_venc"], "tipo": "datetime64[us]"},
    "id_subclasse": {"nomes_origem": ["id_subclasse"], "tipo": "string"},
    "cnpj_fundo_cota": {"nomes_origem": ["cnpj_fundo_cota"], "tipo": "string"},
    "nm_fundo_cota": {"nomes_origem": ["nm_fundo_cota"], "tipo": "string"},
    "cd_swap": {"nomes_origem": ["cd_swap"], "tipo": "string"},
    "ds_swap": {"nomes_origem": ["ds_swap"], "tipo": "string"},
    "cd_ativo": {"nomes_origem": ["cd_ativo"], "tipo": "string"},
    "ds_ativo": {"nomes_origem": ["ds_ativo"], "tipo": "string"},
    "dt_ini_vigencia": {"nomes_origem": ["dt_ini_vigencia"], "tipo": "datetime64[us]"},
    "dt_fim_vigencia": {"nomes_origem": ["dt_fim_vigencia"], "tipo": "datetime64[us]"},
    "cpf_cnpj_emissor": {"nomes_origem": ["cpf_cnpj_emissor"], "tipo": "string"},
    "nm_emissor": {"nomes_origem": ["nm_emissor"], "tipo": "string"},
    "pf_pj_emissor": {"nomes_origem": ["pf_pj_emissor"], "tipo": "string"},
    "ag_risco": {"nomes_origem": ["ag_risco"], "tipo": "string"},
    "grau_risco": {"nomes_origem": ["grau_risco"], "tipo": "string"},
    "dt_risco": {"nomes_origem": ["dt_risco"], "tipo": "datetime64[us]"},
    "risco_emissor": {"nomes_origem": ["risco_emissor"], "tipo": "string"},
    "cd_indexador_posfx": {"nomes_origem": ["cd_indexador_posfx"], "tipo": "string"},
    "ds_indexador_posfx": {"nomes_origem": ["ds_indexador_posfx"], "tipo": "string"},
    "titulo_posfx": {"nomes_origem": ["titulo_posfx"], "tipo": "string"},
    "pr_cupom_posfx": {"nomes_origem": ["pr_cupom_posfx"], "tipo": "float64"},
    "pr_indexador_posfx": {"nomes_origem": ["pr_indexador_posfx"], "tipo": "float64"},
    "pr_taxa_prefx": {"nomes_origem": ["pr_taxa_prefx"], "tipo": "float64"},
    "cnpj_coobrigacao": {"nomes_origem": ["cnpj_coobrigacao"], "tipo": "string"},
    "titulo_cetip": {"nomes_origem": ["titulo_cetip"], "tipo": "string"},
    "titulo_garantia": {"nomes_origem": ["titulo_garantia"], "tipo": "string"},
    "cd_pais": {"nomes_origem": ["cd_pais"], "tipo": "string"},
    "pais": {"nomes_origem": ["pais"], "tipo": "string"},
    "bv_merc": {"nomes_origem": ["bv_merc"], "tipo": "string"},
    "cd_bv_merc": {"nomes_origem": ["cd_bv_merc"], "tipo": "string"},
    "cd_ativo_bv_merc": {"nomes_origem": ["cd_ativo_bv_merc"], "tipo": "string"},
    "ds_ativo_exterior": {"nomes_origem": ["ds_ativo_exterior"], "tipo": "string"},
    "invest_coletivo": {"nomes_origem": ["invest_coletivo"], "tipo": "string"},
    "invest_coletivo_gestor": {"nomes_origem": ["invest_coletivo_gestor"], "tipo": "string"},
    "qt_ativo_exterior": {"nomes_origem": ["qt_ativo_exterior"], "tipo": "float64"},
    "vl_ativo_exterior": {"nomes_origem": ["vl_ativo_exterior"], "tipo": "float64"},
    "qt_aquis_negoc": {"nomes_origem": ["qt_aquis_negoc"], "tipo": "float64"},
    "qt_pos_final": {"nomes_origem": ["qt_pos_final"], "tipo": "float64"},
    "qt_venda_negoc": {"nomes_origem": ["qt_venda_negoc"], "tipo": "float64"},
    "vl_aquis_negoc": {"nomes_origem": ["vl_aquis_negoc"], "tipo": "float64"},
    "vl_custo_pos_final": {"nomes_origem": ["vl_custo_pos_final"], "tipo": "float64"},
    "vl_merc_pos_final": {"nomes_origem": ["vl_merc_pos_final"], "tipo": "float64"},
    "vl_venda_negoc": {"nomes_origem": ["vl_venda_negoc"], "tipo": "float64"},
    "timestamp_dagrun": {"nomes_origem": ["timestamp_dagrun"], "tipo": "datetime64[us]"},
    "timestamp_escrita": {"nomes_origem": ["timestamp_escrita"], "tipo": "datetime64[us]"},
}
