_META = {
    "ano_particao": {"nomes_origem": ["ano_particao"], "tipo": "int32"},
    "mes_particao": {"nomes_origem": ["mes_particao"], "tipo": "int32"},
    "timestamp_dagrun": {"nomes_origem": ["timestamp_dagrun"], "tipo": "datetime64[us]"},
    "timestamp_escrita": {"nomes_origem": ["timestamp_escrita"], "tipo": "datetime64[us]"},
}

_COMMON = {
    "CNPJ_FUNDO_CLASSE": {"nomes_origem": ["CNPJ_FUNDO_CLASSE"], "tipo": "string"},
    "DENOM_SOCIAL": {"nomes_origem": ["DENOM_SOCIAL"], "tipo": "string"},
    "DT_COMPTC": {"nomes_origem": ["DT_COMPTC"], "tipo": "string"},
    "DT_CONFID_APLIC": {"nomes_origem": ["DT_CONFID_APLIC"], "tipo": "string"},
    "EMISSOR_LIGADO": {"nomes_origem": ["EMISSOR_LIGADO"], "tipo": "string"},
    "QT_AQUIS_NEGOC": {"nomes_origem": ["QT_AQUIS_NEGOC"], "tipo": "string"},
    "QT_POS_FINAL": {"nomes_origem": ["QT_POS_FINAL"], "tipo": "string"},
    "QT_VENDA_NEGOC": {"nomes_origem": ["QT_VENDA_NEGOC"], "tipo": "string"},
    "TP_APLIC": {"nomes_origem": ["TP_APLIC"], "tipo": "string"},
    "TP_ATIVO": {"nomes_origem": ["TP_ATIVO"], "tipo": "string"},
    "TP_FUNDO_CLASSE": {"nomes_origem": ["TP_FUNDO_CLASSE"], "tipo": "string"},
    "TP_NEGOC": {"nomes_origem": ["TP_NEGOC"], "tipo": "string"},
    "VL_AQUIS_NEGOC": {"nomes_origem": ["VL_AQUIS_NEGOC"], "tipo": "string"},
    "VL_CUSTO_POS_FINAL": {"nomes_origem": ["VL_CUSTO_POS_FINAL"], "tipo": "string"},
    "VL_MERC_POS_FINAL": {"nomes_origem": ["VL_MERC_POS_FINAL"], "tipo": "string"},
    "VL_VENDA_NEGOC": {"nomes_origem": ["VL_VENDA_NEGOC"], "tipo": "string"},
}

SCHEMAS_BRONZE = {
    "blc_1": {
        **_COMMON,
        "CD_ISIN": {"nomes_origem": ["CD_ISIN"], "tipo": "string"},
        "CD_SELIC": {"nomes_origem": ["CD_SELIC"], "tipo": "string"},
        "DT_EMISSAO": {"nomes_origem": ["DT_EMISSAO"], "tipo": "string"},
        "DT_VENC": {"nomes_origem": ["DT_VENC"], "tipo": "string"},
        "TP_TITPUB": {"nomes_origem": ["TP_TITPUB"], "tipo": "string"},
        **_META,
    },
    "blc_2": {
        **_COMMON,
        "CNPJ_FUNDO_CLASSE_COTA": {"nomes_origem": ["CNPJ_FUNDO_CLASSE_COTA"], "tipo": "string"},
        "ID_SUBCLASSE": {"nomes_origem": ["ID_SUBCLASSE"], "tipo": "string"},
        "NM_FUNDO_CLASSE_SUBCLASSE_COTA": {"nomes_origem": ["NM_FUNDO_CLASSE_SUBCLASSE_COTA"], "tipo": "string"},
        **_META,
    },
    "blc_3": {
        **_COMMON,
        "CD_SWAP": {"nomes_origem": ["CD_SWAP"], "tipo": "string"},
        "DS_SWAP": {"nomes_origem": ["DS_SWAP"], "tipo": "string"},
        **_META,
    },
    "blc_4": {
        **_COMMON,
        "CD_ATIVO": {"nomes_origem": ["CD_ATIVO"], "tipo": "string"},
        "CD_ISIN": {"nomes_origem": ["CD_ISIN"], "tipo": "string"},
        "DS_ATIVO": {"nomes_origem": ["DS_ATIVO"], "tipo": "string"},
        "DT_FIM_VIGENCIA": {"nomes_origem": ["DT_FIM_VIGENCIA"], "tipo": "string"},
        "DT_INI_VIGENCIA": {"nomes_origem": ["DT_INI_VIGENCIA"], "tipo": "string"},
        **_META,
    },
    "blc_5": {
        **_COMMON,
        "AG_RISCO": {"nomes_origem": ["AG_RISCO"], "tipo": "string"},
        "CD_INDEXADOR_POSFX": {"nomes_origem": ["CD_INDEXADOR_POSFX"], "tipo": "string"},
        "CNPJ_EMISSOR": {"nomes_origem": ["CNPJ_EMISSOR"], "tipo": "string"},
        "DS_INDEXADOR_POSFX": {"nomes_origem": ["DS_INDEXADOR_POSFX"], "tipo": "string"},
        "DT_RISCO": {"nomes_origem": ["DT_RISCO"], "tipo": "string"},
        "DT_VENC": {"nomes_origem": ["DT_VENC"], "tipo": "string"},
        "EMISSOR": {"nomes_origem": ["EMISSOR"], "tipo": "string"},
        "GRAU_RISCO": {"nomes_origem": ["GRAU_RISCO"], "tipo": "string"},
        "PR_CUPOM_POSFX": {"nomes_origem": ["PR_CUPOM_POSFX"], "tipo": "string"},
        "PR_INDEXADOR_POSFX": {"nomes_origem": ["PR_INDEXADOR_POSFX"], "tipo": "string"},
        "PR_TAXA_PREFX": {"nomes_origem": ["PR_TAXA_PREFX"], "tipo": "string"},
        "RISCO_EMISSOR": {"nomes_origem": ["RISCO_EMISSOR"], "tipo": "string"},
        "TITULO_POSFX": {"nomes_origem": ["TITULO_POSFX"], "tipo": "string"},
        **_META,
    },
    "blc_6": {
        **_COMMON,
        "CD_INDEXADOR_POSFX": {"nomes_origem": ["CD_INDEXADOR_POSFX"], "tipo": "string"},
        "CNPJ_INSTITUICAO_FINANC_COOBR": {"nomes_origem": ["CNPJ_INSTITUICAO_FINANC_COOBR"], "tipo": "string"},
        "CPF_CNPJ_EMISSOR": {"nomes_origem": ["CPF_CNPJ_EMISSOR"], "tipo": "string"},
        "DS_INDEXADOR_POSFX": {"nomes_origem": ["DS_INDEXADOR_POSFX"], "tipo": "string"},
        "DT_VENC": {"nomes_origem": ["DT_VENC"], "tipo": "string"},
        "EMISSOR": {"nomes_origem": ["EMISSOR"], "tipo": "string"},
        "PF_PJ_EMISSOR": {"nomes_origem": ["PF_PJ_EMISSOR"], "tipo": "string"},
        "PR_CUPOM_POSFX": {"nomes_origem": ["PR_CUPOM_POSFX"], "tipo": "string"},
        "PR_INDEXADOR_POSFX": {"nomes_origem": ["PR_INDEXADOR_POSFX"], "tipo": "string"},
        "PR_TAXA_PREFX": {"nomes_origem": ["PR_TAXA_PREFX"], "tipo": "string"},
        "TITULO_CETIP": {"nomes_origem": ["TITULO_CETIP"], "tipo": "string"},
        "TITULO_GARANTIA": {"nomes_origem": ["TITULO_GARANTIA"], "tipo": "string"},
        "TITULO_POSFX": {"nomes_origem": ["TITULO_POSFX"], "tipo": "string"},
        **_META,
    },
    "blc_7": {
        **_COMMON,
        "AG_RISCO": {"nomes_origem": ["AG_RISCO"], "tipo": "string"},
        "BV_MERC": {"nomes_origem": ["BV_MERC"], "tipo": "string"},
        "CD_ATIVO_BV_MERC": {"nomes_origem": ["CD_ATIVO_BV_MERC"], "tipo": "string"},
        "CD_BV_MERC": {"nomes_origem": ["CD_BV_MERC"], "tipo": "string"},
        "CD_PAIS": {"nomes_origem": ["CD_PAIS"], "tipo": "string"},
        "DS_ATIVO_EXTERIOR": {"nomes_origem": ["DS_ATIVO_EXTERIOR"], "tipo": "string"},
        "DT_RISCO": {"nomes_origem": ["DT_RISCO"], "tipo": "string"},
        "DT_VENC": {"nomes_origem": ["DT_VENC"], "tipo": "string"},
        "EMISSOR": {"nomes_origem": ["EMISSOR"], "tipo": "string"},
        "GRAU_RISCO": {"nomes_origem": ["GRAU_RISCO"], "tipo": "string"},
        "INVEST_COLETIVO": {"nomes_origem": ["INVEST_COLETIVO"], "tipo": "string"},
        "INVEST_COLETIVO_GESTOR": {"nomes_origem": ["INVEST_COLETIVO_GESTOR"], "tipo": "string"},
        "PAIS": {"nomes_origem": ["PAIS"], "tipo": "string"},
        "QT_ATIVO_EXTERIOR": {"nomes_origem": ["QT_ATIVO_EXTERIOR"], "tipo": "string"},
        "RISCO_EMISSOR": {"nomes_origem": ["RISCO_EMISSOR"], "tipo": "string"},
        "VL_ATIVO_EXTERIOR": {"nomes_origem": ["VL_ATIVO_EXTERIOR"], "tipo": "string"},
        **_META,
    },
    "blc_8": {
        **_COMMON,
        "CPF_CNPJ_EMISSOR": {"nomes_origem": ["CPF_CNPJ_EMISSOR"], "tipo": "string"},
        "DS_ATIVO": {"nomes_origem": ["DS_ATIVO"], "tipo": "string"},
        "EMISSOR": {"nomes_origem": ["EMISSOR"], "tipo": "string"},
        "PF_PJ_EMISSOR": {"nomes_origem": ["PF_PJ_EMISSOR"], "tipo": "string"},
        **_META,
    },
}
