SCHEMA_SILVER_RENTAB_MES = {
    "cnpj_fundo": {"nomes_origem": ["CNPJ_FUNDO_CLASSE"], "tipo": "string"},
    "denom_social": {"nomes_origem": ["DENOM_SOCIAL"], "tipo": "string"},
    "tp_fundo_classe": {"nomes_origem": ["TP_FUNDO_CLASSE"], "tipo": "string"},
    "id_subclasse": {"nomes_origem": ["ID_SUBCLASSE"], "tipo": "string"},
    "dt_comptc": {"nomes_origem": ["DT_COMPTC"], "tipo": "datetime64[us]"},
    "mes_rentab": {"nomes_origem": ["MES_RENTAB"], "tipo": "int8"},
    "pr_rentab_mes": {"nomes_origem": ["PR_RENTAB_MES"], "tipo": "float64"},
    "pr_variacao_indice_refer_mes": {"nomes_origem": ["PR_VARIACAO_INDICE_REFER_MES"], "tipo": "float64"},
    "pr_perfm_indice_refer_mes": {"nomes_origem": ["PR_PERFM_INDICE_REFER_MES"], "tipo": "float64"},
    "rentab_mes_obs": {"nomes_origem": ["RENTAB_MES_OBS"], "tipo": "string"},
    "ano_particao": {"nomes_origem": ["ano_particao"], "tipo": "int16"},
    "mes_particao": {"nomes_origem": ["mes_particao"], "tipo": "int8"},
    "timestamp_dagrun": {"nomes_origem": ["timestamp_dagrun"], "tipo": "datetime64[us]"},
    "timestamp_escrita": {"nomes_origem": ["timestamp_escrita"], "tipo": "datetime64[us]"},
}
